### ISSUE TITLE
Unknown reasons for the failure in verifying the Groth16 proof

### ISSUE THREAD

**Issue by weikengchen** [arkworks-rs/ivls#7]
During the process to replace `rand`, we encounter an issue where the HelpCircuit's constraint system is not satisfactory.

This error is not triggered yesterday and based on the current attempts, it is likely due to other repos. We have not yet unveiled what the cause is. 

Since `ivls` depends on a large number of repos, it is hard to conduct the debugging. I will start to take a look later this week after my other obligations are met. Likely I will start from PCD. We may have to go all the way back to algebra if FFT is indeed the reason.

**Comment by Pratyush** [comment]
Are the tests in the Groth16 repo passing?

**Comment by weikengchen** [comment]
Yes, tests in PCD and Groth16 are both passing.

But IVLS even before the commit before your commit is failing.

**Comment by weikengchen** [comment]
So, I need to dig deeper. One of my guesses is whether the problem only pops up when the FFT instance is sufficiently large or very close to something.

**Comment by Pratyush** [comment]
Do you know what the size of the constraint system is here?

**Comment by weikengchen** [comment]
Let me quickly find a number...

**Comment by weikengchen** [comment]
It appears that the number is about 218246 for MainCircuit and 33322 for HelpCircuit. These seem to be some common sizes and are likely not the reasons for failing.

Groth16 verifier constraint is where it fails. In other words, when I removed the Groth16 verifier from both MainCircuit and HelpCircuit, PCD no longer complains that the constraint system is not satisfactory, but the final proof is not verified outside either. 

The next step of my testing is likely to see if both raw proofs can be verified outside SNARK---if it cannot, then likely there is an issue with Groth16. If it can, then there is likely a problem with the Groth16 verifier gadget.

**Comment by Pratyush** [comment]
@weikengchen maybe this is the issue: https://github.com/arkworks-rs/algebra/issues/243 ?

**Comment by weikengchen** [comment]
More info:
 - Groth16 prover/verifier passes for 300k constraints.
 - Groth16 verifier circuit passes for 300k constraints. 
 
It seems that arkworks-rs/algebra#243 may be very related. So I will likely wait on that one...

**Comment by Pratyush** [comment]
@weikengchen Do these tests pass now?

**Comment by Pratyush** [comment]
The tests do indeed pass, so that should resolve this issue!

**Comment by weikengchen** [comment]
It passes!
